FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-8-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

RUN wget -qO - https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.1.x/32/deb/6.1/archive.key | sudo apt-key add - && \
   add-apt-repository "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.1.x/32/deb/6.1 stable main" && \
   apt-get update

RUN apt-get install --yes \
     confluent-common=6.1.0-1 \
     confluent-hub-client=6.1.0-1 \
     confluent-rebalancer=6.1.0-1 \
     confluent-rest-utils=6.1.0-1 \
     confluent-metadata-service=6.1.0-1 \
     confluent-server=6.1.0-1 \
     confluent-kafka-connect-replicator=6.1.0-1 \
     confluent-kafka-rest=6.1.0-1 \
     confluent-ksqldb=6.1.0-1 \
     confluent-schema-registry=6.1.0-1 \
     confluent-security=6.1.0-1 \
     confluent-control-center-fe=6.1.0-1 \
     confluent-control-center=6.1.0-1 \
     confluent-schema-registry=6.1.0-1

